### ISSUE TITLE
How to modify prompt?

### ISSUE THREAD

**Issue by andyr** [wadey/dotfiles#1]
This is just a question (not a bug).  

I'd like to insert a newline between the [git branch/status] and the prompt character (%).  I don't see any variables setting PS1, PS2 and PS4 in my zshrc

**Comment by wadey** [comment]
The prompt is set up in this file: https://github.com/wadey/dotfiles/blob/2ce51f99700ad4b66049594eace5eceab92da7a6/zsh/wadey.zsh-theme#L23

You can either edit that file directly or create a copy of it with a new name and change the theme name here: https://github.com/wadey/dotfiles/blob/2ce51f99700ad4b66049594eace5eceab92da7a6/zshrc#L14

**Comment by andyr** [comment]
Thank you!

**Comment by aguynamedben** [comment]
@wadey is my hero
